import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from "next/link";
import { getDatabase } from "../lib/notion";
// import styles from "../styles/notion-posts.module.css";
import {Text} from "../components/notion/Text";

// import slugify from "slugify";

export const databaseId = process.env.NOTION_DATABASE_ID;

export default function Home({ posts }) {
  console.log("posts", posts);
  if (posts == null) {
    return (
        <h1>Loading...</h1>
    );
  }
  // slugify(post.properties.Name.title[0].text.content)
  return (


  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <span>Happy writes</span>!
      </h1>
      <p className={styles.description}>
        I'm Happy, I'd like to share my thoughts with you
      </p>
      <div className={styles.grid}>
          {posts.map((post) => (
            <span key={post.id} className={styles.card}>
              <Link href={`/${post.id}`}>
                <a>
                 <h2><Text text={post.properties.Name.title} /> </h2>
                </a>
              </Link>
            </span>
          ))}
      </div>
    </main>

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </a>
    </footer>
  </div>

  );
}

export const getStaticProps = async () => {
  const database = await getDatabase(databaseId);

  return {
    props: {
      posts: database,
    },
  };
};
